name: Run tests
on: [push, pull_request]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version:
          [
            2.1,
            2.2,
            2.3,
            2.4,
            2.5,
            2.6,
            2.7,
            jruby,
          ]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}
      - name: ruby version
        run: ruby -v
      - run: bundler install
        name: install
      - run: bundler exec rake -t
        name: test
